# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # For Node.js/JavaScript projects
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "orguetta"
    assignees:
      - "orguetta"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "github-actions" # For GitHub Actions workflows
    directory: "/" # Location of workflow files
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "orguetta"
    assignees:
      - "orguetta"
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
