name: Generate Resume PDF

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/pages/resume.md'
      - 'public/resume/resume-stylesheet.css'
      - '.github/workflows/resume-pdf.yml'
      - 'scripts/generate-pandoc-resume.mjs'

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install gray-matter

      - name: Prepare Markdown for Pandoc
        run: node scripts/generate-pandoc-resume.mjs

      - name: Install Pandoc and wkhtmltopdf
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.6.4/pandoc-3.6.4-1-amd64.deb
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          sudo apt install ./pandoc-3.6.4-1-amd64.deb
          sudo apt install ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb

      - name: Convert MD to HTML
        run: |
          pandoc temp-resume.md -f markdown -t html -c public/resume/resume-stylesheet.css -s -o resume.html

      - name: Convert HTML to PDF
        run: |
          wkhtmltopdf --enable-local-file-access resume.html public/resume.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: public/resume.pdf

      - name: Commit PDF (optional)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/resume.pdf
          git commit -m "Auto-generate resume PDF" || echo "No changes to commit"
          git push
